matrix:
  include:
  - name: Docker - Build the Modules' Jars, Run all Java tests, Create vital containers, Check if they stay alive for more than 20 seconds
    language: bash
    sudo: required
    services:
    - docker
    before_install:
    - docker -v
    - docker-compose -v
    - cp .travis/.env docker/.env
    install:
    - echo "Hello World!"
    script:
    - ( cd docker && echo "test" )
    - pwd
    - ( cd docker && docker build -t steady-pipeline:${VULAS_RELEASE} pipeline )
